import random2
from time import sleep
print("-"*30)
print("(bot1)digite o numero 6 para parar")
print("-"*30)
while True:
          esc1=(random2.randint(1,5))          
          sleep(1.5)
          print("-"*30)
          print("(bot1) que numero pensei?")
          print("-"*30)
          esc2=(random2.randint(1,6))
          sleep(1.5)
          print("-"*30)
          print("(bot2) vc pensou no numero {}".format(esc2))
          print("-"*30)
          if esc1!=esc2 and esc2 !=6:
              sleep(1.5)
              print("-"*30)
              print("(bot1)errou 🫵🤣🤣🤣kkk o resultado e {}".format(esc1))
              print("-"*30)         
          elif esc1==esc2:
              sleep(1.5)
              print("-"*30)
              print("parabens acertou  ")
              print("-"*30)
          elif esc2==6:
              sleep(1.5)
              print("-"*30)
              print("(bot2) estou fora seu batoteiro 😡")
              print("-"*30)
              sleep(1.5)
              print("-"*30)
              print("(bot1) ate mais covarde 🤣🤣 ")
              print("-"*30)
              sleep(1.5)
              print("-"*30)
              print('(bot2) 🖕')
              print("-"*30)
              sleep(1.5)
              print("-"*30)
              print('(bot1) 🤣🤣🤣🤣🤣🤣🤣🤣 ')
              print("-"*30)
              break              
